version: '3'
services:
  next-app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env  
    stdin_open: true
    tty: true
    command: sh -c "npm install && npm dev"
